root: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
  - plugin:import/recommended
  - plugin:import/typescript
  - plugin:react/recommended
  - plugin:react-hooks/recommended
  - plugin:jsx-a11y/recommended
  - plugin:jest/recommended
  - plugin:testing-library/react
  - prettier
parserOptions:
  project: ./tsconfig.json
env:
  browser: true
  es2021: true
rules:
  import/prefer-default-export: off
  import/no-default-export: error
settings:
  react:
    version: detect
